keys:
  - &primary age1hv4jv7ju02psre8pxed3ea9cjl7l65sv5rvphadzxkymg2fuzd0qrm758v
creation_rules:
  # Match any .yaml files in secrets directory (including temporary files)
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *primary
